import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const inter = Poppins({ subsets: ["latin"],weight:["100","200","300","500"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className+` flex flex-col w-full h-screen justify-between items-center bg-slate-200`}>
              <NavBar />
              <main className="flex-grow w-full">
            {children}
              </main>
              <footer className="mt-5">
                Books | 2024
              </footer>
            </body>
        </html>
    );
}
